---

- name: install zsh
  apt: pkg=zsh state=present

- name: install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~{{user}}/.oh-my-zsh
  sudo: false

- name: Check if there is already an existing ~/.zshrc
  stat: path=~{{user}}/.zshrc
  register: check_path

- name: ~/.zshrc found
  copy: src=~{{user}}/.zshrc dest=~{{user}}/.zshrc.orig
  sudo: false
  when: check_path.stat.exists

- name: Creating new ~/.zshrc
  copy: src=~{{user}}/.oh-my-zsh/templates/zshrc.zsh-template dest=~{{user}}/.zshrc
  sudo: false

- name: switch to ZSH
  user: name={{user}} shell=/usr/bin/zsh
  sudo: True
